fragment EventParts on Event {
  __typename
  title
  date
  description
  link
  image
  isLive
  category
  order
}

fragment OfficeHoursParts on OfficeHours {
  __typename
  sessions {
    __typename
    title
    performer
    designation
    description
    date
    link
    interestGroups
    poster_thumbnail
  }
}

fragment SaltMangoTreeParts on SaltMangoTree {
  __typename
  episodes {
    __typename
    topic
    campus
    zone
    date
    description
    link
  }
}

fragment InspirationStationParts on InspirationStation {
  __typename
  episodes {
    __typename
    topic
    campus
    zone
    date
    description
    link
  }
}

fragment SpecialEventParts on SpecialEvent {
  __typename
  title
  description
  link
  image
  isLive
  order
}
