//@ts-nocheck
// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
export function gql(strings: TemplateStringsArray, ...args: string[]): string {
  let str = "";
  strings.forEach((string, i) => {
    str += string + (args[i] || "");
  });
  return str;
}
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = {
  [_ in K]?: never;
};
export type Incremental<T> =
  | T
  | { [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any };
  JSON: { input: any; output: any };
};

export type SystemInfo = {
  __typename?: "SystemInfo";
  filename: Scalars["String"]["output"];
  title?: Maybe<Scalars["String"]["output"]>;
  basename: Scalars["String"]["output"];
  hasReferences?: Maybe<Scalars["Boolean"]["output"]>;
  breadcrumbs: Array<Scalars["String"]["output"]>;
  path: Scalars["String"]["output"];
  relativePath: Scalars["String"]["output"];
  extension: Scalars["String"]["output"];
  template: Scalars["String"]["output"];
  collection: Collection;
};

export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars["Boolean"]["input"]>;
};

export type Folder = {
  __typename?: "Folder";
  name: Scalars["String"]["output"];
  path: Scalars["String"]["output"];
};

export type PageInfo = {
  __typename?: "PageInfo";
  hasPreviousPage: Scalars["Boolean"]["output"];
  hasNextPage: Scalars["Boolean"]["output"];
  startCursor: Scalars["String"]["output"];
  endCursor: Scalars["String"]["output"];
};

export type Node = {
  id: Scalars["ID"]["output"];
};

export type Document = {
  id: Scalars["ID"]["output"];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars["JSON"]["output"];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars["Float"]["output"];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: "Query";
  getOptimizedQuery?: Maybe<Scalars["String"]["output"]>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  event: Event;
  eventConnection: EventConnection;
  officeHours: OfficeHours;
  officeHoursConnection: OfficeHoursConnection;
  saltMangoTree: SaltMangoTree;
  saltMangoTreeConnection: SaltMangoTreeConnection;
  inspirationStation: InspirationStation;
  inspirationStationConnection: InspirationStationConnection;
  specialEvent: SpecialEvent;
  specialEventConnection: SpecialEventConnection;
};

export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars["String"]["input"];
};

export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryNodeArgs = {
  id?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryEventArgs = {
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryEventConnectionArgs = {
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<EventFilter>;
};

export type QueryOfficeHoursArgs = {
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryOfficeHoursConnectionArgs = {
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<OfficeHoursFilter>;
};

export type QuerySaltMangoTreeArgs = {
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type QuerySaltMangoTreeConnectionArgs = {
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<SaltMangoTreeFilter>;
};

export type QueryInspirationStationArgs = {
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryInspirationStationConnectionArgs = {
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<InspirationStationFilter>;
};

export type QuerySpecialEventArgs = {
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type QuerySpecialEventConnectionArgs = {
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<SpecialEventFilter>;
};

export type DocumentFilter = {
  event?: InputMaybe<EventFilter>;
  officeHours?: InputMaybe<OfficeHoursFilter>;
  saltMangoTree?: InputMaybe<SaltMangoTreeFilter>;
  inspirationStation?: InputMaybe<InspirationStationFilter>;
  specialEvent?: InputMaybe<SpecialEventFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: "DocumentConnectionEdges";
  cursor: Scalars["String"]["output"];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: "DocumentConnection";
  pageInfo: PageInfo;
  totalCount: Scalars["Float"]["output"];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: "Collection";
  name: Scalars["String"]["output"];
  slug: Scalars["String"]["output"];
  label?: Maybe<Scalars["String"]["output"]>;
  path: Scalars["String"]["output"];
  format?: Maybe<Scalars["String"]["output"]>;
  matches?: Maybe<Scalars["String"]["output"]>;
  templates?: Maybe<Array<Maybe<Scalars["JSON"]["output"]>>>;
  fields?: Maybe<Array<Maybe<Scalars["JSON"]["output"]>>>;
  documents: DocumentConnection;
};

export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars["String"]["input"]>;
};

export type DocumentNode =
  | Event
  | OfficeHours
  | SaltMangoTree
  | InspirationStation
  | SpecialEvent
  | Folder;

export type Event = Node &
  Document & {
    __typename?: "Event";
    title: Scalars["String"]["output"];
    date?: Maybe<Scalars["String"]["output"]>;
    description?: Maybe<Scalars["String"]["output"]>;
    link?: Maybe<Scalars["String"]["output"]>;
    image?: Maybe<Scalars["String"]["output"]>;
    isLive?: Maybe<Scalars["Boolean"]["output"]>;
    category: Scalars["String"]["output"];
    order?: Maybe<Scalars["Float"]["output"]>;
    id: Scalars["ID"]["output"];
    _sys: SystemInfo;
    _values: Scalars["JSON"]["output"];
  };

export type StringFilter = {
  startsWith?: InputMaybe<Scalars["String"]["input"]>;
  eq?: InputMaybe<Scalars["String"]["input"]>;
  exists?: InputMaybe<Scalars["Boolean"]["input"]>;
  in?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars["String"]["input"]>;
  eq?: InputMaybe<Scalars["String"]["input"]>;
  exists?: InputMaybe<Scalars["Boolean"]["input"]>;
  in?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars["Boolean"]["input"]>;
  exists?: InputMaybe<Scalars["Boolean"]["input"]>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars["Float"]["input"]>;
  lte?: InputMaybe<Scalars["Float"]["input"]>;
  gte?: InputMaybe<Scalars["Float"]["input"]>;
  gt?: InputMaybe<Scalars["Float"]["input"]>;
  eq?: InputMaybe<Scalars["Float"]["input"]>;
  exists?: InputMaybe<Scalars["Boolean"]["input"]>;
  in?: InputMaybe<Array<InputMaybe<Scalars["Float"]["input"]>>>;
};

export type EventFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  isLive?: InputMaybe<BooleanFilter>;
  category?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type EventConnectionEdges = {
  __typename?: "EventConnectionEdges";
  cursor: Scalars["String"]["output"];
  node?: Maybe<Event>;
};

export type EventConnection = Connection & {
  __typename?: "EventConnection";
  pageInfo: PageInfo;
  totalCount: Scalars["Float"]["output"];
  edges?: Maybe<Array<Maybe<EventConnectionEdges>>>;
};

export type OfficeHoursSessions = {
  __typename?: "OfficeHoursSessions";
  title: Scalars["String"]["output"];
  performer?: Maybe<Scalars["String"]["output"]>;
  designation?: Maybe<Scalars["String"]["output"]>;
  description?: Maybe<Scalars["String"]["output"]>;
  date: Scalars["String"]["output"];
  link?: Maybe<Scalars["String"]["output"]>;
  interestGroups?: Maybe<Array<Maybe<Scalars["String"]["output"]>>>;
  poster_thumbnail?: Maybe<Scalars["String"]["output"]>;
};

export type OfficeHours = Node &
  Document & {
    __typename?: "OfficeHours";
    sessions?: Maybe<Array<Maybe<OfficeHoursSessions>>>;
    id: Scalars["ID"]["output"];
    _sys: SystemInfo;
    _values: Scalars["JSON"]["output"];
  };

export type OfficeHoursSessionsFilter = {
  title?: InputMaybe<StringFilter>;
  performer?: InputMaybe<StringFilter>;
  designation?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  interestGroups?: InputMaybe<StringFilter>;
  poster_thumbnail?: InputMaybe<ImageFilter>;
};

export type OfficeHoursFilter = {
  sessions?: InputMaybe<OfficeHoursSessionsFilter>;
};

export type OfficeHoursConnectionEdges = {
  __typename?: "OfficeHoursConnectionEdges";
  cursor: Scalars["String"]["output"];
  node?: Maybe<OfficeHours>;
};

export type OfficeHoursConnection = Connection & {
  __typename?: "OfficeHoursConnection";
  pageInfo: PageInfo;
  totalCount: Scalars["Float"]["output"];
  edges?: Maybe<Array<Maybe<OfficeHoursConnectionEdges>>>;
};

export type SaltMangoTreeEpisodes = {
  __typename?: "SaltMangoTreeEpisodes";
  topic: Scalars["String"]["output"];
  campus: Scalars["String"]["output"];
  zone?: Maybe<Scalars["String"]["output"]>;
  date: Scalars["String"]["output"];
  description?: Maybe<Scalars["String"]["output"]>;
  link?: Maybe<Scalars["String"]["output"]>;
};

export type SaltMangoTree = Node &
  Document & {
    __typename?: "SaltMangoTree";
    episodes?: Maybe<Array<Maybe<SaltMangoTreeEpisodes>>>;
    id: Scalars["ID"]["output"];
    _sys: SystemInfo;
    _values: Scalars["JSON"]["output"];
  };

export type SaltMangoTreeEpisodesFilter = {
  topic?: InputMaybe<StringFilter>;
  campus?: InputMaybe<StringFilter>;
  zone?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type SaltMangoTreeFilter = {
  episodes?: InputMaybe<SaltMangoTreeEpisodesFilter>;
};

export type SaltMangoTreeConnectionEdges = {
  __typename?: "SaltMangoTreeConnectionEdges";
  cursor: Scalars["String"]["output"];
  node?: Maybe<SaltMangoTree>;
};

export type SaltMangoTreeConnection = Connection & {
  __typename?: "SaltMangoTreeConnection";
  pageInfo: PageInfo;
  totalCount: Scalars["Float"]["output"];
  edges?: Maybe<Array<Maybe<SaltMangoTreeConnectionEdges>>>;
};

export type InspirationStationEpisodes = {
  __typename?: "InspirationStationEpisodes";
  topic: Scalars["String"]["output"];
  campus: Scalars["String"]["output"];
  zone?: Maybe<Scalars["String"]["output"]>;
  date: Scalars["String"]["output"];
  description?: Maybe<Scalars["String"]["output"]>;
  link?: Maybe<Scalars["String"]["output"]>;
};

export type InspirationStation = Node &
  Document & {
    __typename?: "InspirationStation";
    episodes?: Maybe<Array<Maybe<InspirationStationEpisodes>>>;
    id: Scalars["ID"]["output"];
    _sys: SystemInfo;
    _values: Scalars["JSON"]["output"];
  };

export type InspirationStationEpisodesFilter = {
  topic?: InputMaybe<StringFilter>;
  campus?: InputMaybe<StringFilter>;
  zone?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type InspirationStationFilter = {
  episodes?: InputMaybe<InspirationStationEpisodesFilter>;
};

export type InspirationStationConnectionEdges = {
  __typename?: "InspirationStationConnectionEdges";
  cursor: Scalars["String"]["output"];
  node?: Maybe<InspirationStation>;
};

export type InspirationStationConnection = Connection & {
  __typename?: "InspirationStationConnection";
  pageInfo: PageInfo;
  totalCount: Scalars["Float"]["output"];
  edges?: Maybe<Array<Maybe<InspirationStationConnectionEdges>>>;
};

export type SpecialEvent = Node &
  Document & {
    __typename?: "SpecialEvent";
    title: Scalars["String"]["output"];
    description?: Maybe<Scalars["String"]["output"]>;
    link?: Maybe<Scalars["String"]["output"]>;
    image?: Maybe<Scalars["String"]["output"]>;
    isLive?: Maybe<Scalars["Boolean"]["output"]>;
    order?: Maybe<Scalars["Float"]["output"]>;
    id: Scalars["ID"]["output"];
    _sys: SystemInfo;
    _values: Scalars["JSON"]["output"];
  };

export type SpecialEventFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  isLive?: InputMaybe<BooleanFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type SpecialEventConnectionEdges = {
  __typename?: "SpecialEventConnectionEdges";
  cursor: Scalars["String"]["output"];
  node?: Maybe<SpecialEvent>;
};

export type SpecialEventConnection = Connection & {
  __typename?: "SpecialEventConnection";
  pageInfo: PageInfo;
  totalCount: Scalars["Float"]["output"];
  edges?: Maybe<Array<Maybe<SpecialEventConnectionEdges>>>;
};

export type Mutation = {
  __typename?: "Mutation";
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateEvent: Event;
  createEvent: Event;
  updateOfficeHours: OfficeHours;
  createOfficeHours: OfficeHours;
  updateSaltMangoTree: SaltMangoTree;
  createSaltMangoTree: SaltMangoTree;
  updateInspirationStation: InspirationStation;
  createInspirationStation: InspirationStation;
  updateSpecialEvent: SpecialEvent;
  createSpecialEvent: SpecialEvent;
};

export type MutationAddPendingDocumentArgs = {
  collection: Scalars["String"]["input"];
  relativePath: Scalars["String"]["input"];
  template?: InputMaybe<Scalars["String"]["input"]>;
};

export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
  relativePath: Scalars["String"]["input"];
  params: DocumentUpdateMutation;
};

export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
  relativePath: Scalars["String"]["input"];
};

export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
  relativePath: Scalars["String"]["input"];
  params: DocumentMutation;
};

export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
  relativePath: Scalars["String"]["input"];
};

export type MutationUpdateEventArgs = {
  relativePath: Scalars["String"]["input"];
  params: EventMutation;
};

export type MutationCreateEventArgs = {
  relativePath: Scalars["String"]["input"];
  params: EventMutation;
};

export type MutationUpdateOfficeHoursArgs = {
  relativePath: Scalars["String"]["input"];
  params: OfficeHoursMutation;
};

export type MutationCreateOfficeHoursArgs = {
  relativePath: Scalars["String"]["input"];
  params: OfficeHoursMutation;
};

export type MutationUpdateSaltMangoTreeArgs = {
  relativePath: Scalars["String"]["input"];
  params: SaltMangoTreeMutation;
};

export type MutationCreateSaltMangoTreeArgs = {
  relativePath: Scalars["String"]["input"];
  params: SaltMangoTreeMutation;
};

export type MutationUpdateInspirationStationArgs = {
  relativePath: Scalars["String"]["input"];
  params: InspirationStationMutation;
};

export type MutationCreateInspirationStationArgs = {
  relativePath: Scalars["String"]["input"];
  params: InspirationStationMutation;
};

export type MutationUpdateSpecialEventArgs = {
  relativePath: Scalars["String"]["input"];
  params: SpecialEventMutation;
};

export type MutationCreateSpecialEventArgs = {
  relativePath: Scalars["String"]["input"];
  params: SpecialEventMutation;
};

export type DocumentUpdateMutation = {
  event?: InputMaybe<EventMutation>;
  officeHours?: InputMaybe<OfficeHoursMutation>;
  saltMangoTree?: InputMaybe<SaltMangoTreeMutation>;
  inspirationStation?: InputMaybe<InspirationStationMutation>;
  specialEvent?: InputMaybe<SpecialEventMutation>;
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type DocumentMutation = {
  event?: InputMaybe<EventMutation>;
  officeHours?: InputMaybe<OfficeHoursMutation>;
  saltMangoTree?: InputMaybe<SaltMangoTreeMutation>;
  inspirationStation?: InputMaybe<InspirationStationMutation>;
  specialEvent?: InputMaybe<SpecialEventMutation>;
};

export type EventMutation = {
  title?: InputMaybe<Scalars["String"]["input"]>;
  date?: InputMaybe<Scalars["String"]["input"]>;
  description?: InputMaybe<Scalars["String"]["input"]>;
  link?: InputMaybe<Scalars["String"]["input"]>;
  image?: InputMaybe<Scalars["String"]["input"]>;
  isLive?: InputMaybe<Scalars["Boolean"]["input"]>;
  category?: InputMaybe<Scalars["String"]["input"]>;
  order?: InputMaybe<Scalars["Float"]["input"]>;
};

export type OfficeHoursSessionsMutation = {
  title?: InputMaybe<Scalars["String"]["input"]>;
  performer?: InputMaybe<Scalars["String"]["input"]>;
  designation?: InputMaybe<Scalars["String"]["input"]>;
  description?: InputMaybe<Scalars["String"]["input"]>;
  date?: InputMaybe<Scalars["String"]["input"]>;
  link?: InputMaybe<Scalars["String"]["input"]>;
  interestGroups?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
  poster_thumbnail?: InputMaybe<Scalars["String"]["input"]>;
};

export type OfficeHoursMutation = {
  sessions?: InputMaybe<Array<InputMaybe<OfficeHoursSessionsMutation>>>;
};

export type SaltMangoTreeEpisodesMutation = {
  topic?: InputMaybe<Scalars["String"]["input"]>;
  campus?: InputMaybe<Scalars["String"]["input"]>;
  zone?: InputMaybe<Scalars["String"]["input"]>;
  date?: InputMaybe<Scalars["String"]["input"]>;
  description?: InputMaybe<Scalars["String"]["input"]>;
  link?: InputMaybe<Scalars["String"]["input"]>;
};

export type SaltMangoTreeMutation = {
  episodes?: InputMaybe<Array<InputMaybe<SaltMangoTreeEpisodesMutation>>>;
};

export type InspirationStationEpisodesMutation = {
  topic?: InputMaybe<Scalars["String"]["input"]>;
  campus?: InputMaybe<Scalars["String"]["input"]>;
  zone?: InputMaybe<Scalars["String"]["input"]>;
  date?: InputMaybe<Scalars["String"]["input"]>;
  description?: InputMaybe<Scalars["String"]["input"]>;
  link?: InputMaybe<Scalars["String"]["input"]>;
};

export type InspirationStationMutation = {
  episodes?: InputMaybe<Array<InputMaybe<InspirationStationEpisodesMutation>>>;
};

export type SpecialEventMutation = {
  title?: InputMaybe<Scalars["String"]["input"]>;
  description?: InputMaybe<Scalars["String"]["input"]>;
  link?: InputMaybe<Scalars["String"]["input"]>;
  image?: InputMaybe<Scalars["String"]["input"]>;
  isLive?: InputMaybe<Scalars["Boolean"]["input"]>;
  order?: InputMaybe<Scalars["Float"]["input"]>;
};

export type EventPartsFragment = {
  __typename: "Event";
  title: string;
  date?: string | null;
  description?: string | null;
  link?: string | null;
  image?: string | null;
  isLive?: boolean | null;
  category: string;
  order?: number | null;
};

export type OfficeHoursPartsFragment = {
  __typename: "OfficeHours";
  sessions?: Array<{
    __typename: "OfficeHoursSessions";
    title: string;
    performer?: string | null;
    designation?: string | null;
    description?: string | null;
    date: string;
    link?: string | null;
    interestGroups?: Array<string | null> | null;
    poster_thumbnail?: string | null;
  } | null> | null;
};

export type SaltMangoTreePartsFragment = {
  __typename: "SaltMangoTree";
  episodes?: Array<{
    __typename: "SaltMangoTreeEpisodes";
    topic: string;
    campus: string;
    zone?: string | null;
    date: string;
    description?: string | null;
    link?: string | null;
  } | null> | null;
};

export type InspirationStationPartsFragment = {
  __typename: "InspirationStation";
  episodes?: Array<{
    __typename: "InspirationStationEpisodes";
    topic: string;
    campus: string;
    zone?: string | null;
    date: string;
    description?: string | null;
    link?: string | null;
  } | null> | null;
};

export type SpecialEventPartsFragment = {
  __typename: "SpecialEvent";
  title: string;
  description?: string | null;
  link?: string | null;
  image?: string | null;
  isLive?: boolean | null;
  order?: number | null;
};

export type EventQueryVariables = Exact<{
  relativePath: Scalars["String"]["input"];
}>;

export type EventQuery = {
  __typename?: "Query";
  event: {
    __typename: "Event";
    id: string;
    title: string;
    date?: string | null;
    description?: string | null;
    link?: string | null;
    image?: string | null;
    isLive?: boolean | null;
    category: string;
    order?: number | null;
    _sys: {
      __typename?: "SystemInfo";
      filename: string;
      basename: string;
      hasReferences?: boolean | null;
      breadcrumbs: Array<string>;
      path: string;
      relativePath: string;
      extension: string;
    };
  };
};

export type EventConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<EventFilter>;
}>;

export type EventConnectionQuery = {
  __typename?: "Query";
  eventConnection: {
    __typename?: "EventConnection";
    totalCount: number;
    pageInfo: {
      __typename?: "PageInfo";
      hasPreviousPage: boolean;
      hasNextPage: boolean;
      startCursor: string;
      endCursor: string;
    };
    edges?: Array<{
      __typename?: "EventConnectionEdges";
      cursor: string;
      node?: {
        __typename: "Event";
        id: string;
        title: string;
        date?: string | null;
        description?: string | null;
        link?: string | null;
        image?: string | null;
        isLive?: boolean | null;
        category: string;
        order?: number | null;
        _sys: {
          __typename?: "SystemInfo";
          filename: string;
          basename: string;
          hasReferences?: boolean | null;
          breadcrumbs: Array<string>;
          path: string;
          relativePath: string;
          extension: string;
        };
      } | null;
    } | null> | null;
  };
};

export type OfficeHoursQueryVariables = Exact<{
  relativePath: Scalars["String"]["input"];
}>;

export type OfficeHoursQuery = {
  __typename?: "Query";
  officeHours: {
    __typename: "OfficeHours";
    id: string;
    _sys: {
      __typename?: "SystemInfo";
      filename: string;
      basename: string;
      hasReferences?: boolean | null;
      breadcrumbs: Array<string>;
      path: string;
      relativePath: string;
      extension: string;
    };
    sessions?: Array<{
      __typename: "OfficeHoursSessions";
      title: string;
      performer?: string | null;
      designation?: string | null;
      description?: string | null;
      date: string;
      link?: string | null;
      interestGroups?: Array<string | null> | null;
      poster_thumbnail?: string | null;
    } | null> | null;
  };
};

export type OfficeHoursConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<OfficeHoursFilter>;
}>;

export type OfficeHoursConnectionQuery = {
  __typename?: "Query";
  officeHoursConnection: {
    __typename?: "OfficeHoursConnection";
    totalCount: number;
    pageInfo: {
      __typename?: "PageInfo";
      hasPreviousPage: boolean;
      hasNextPage: boolean;
      startCursor: string;
      endCursor: string;
    };
    edges?: Array<{
      __typename?: "OfficeHoursConnectionEdges";
      cursor: string;
      node?: {
        __typename: "OfficeHours";
        id: string;
        _sys: {
          __typename?: "SystemInfo";
          filename: string;
          basename: string;
          hasReferences?: boolean | null;
          breadcrumbs: Array<string>;
          path: string;
          relativePath: string;
          extension: string;
        };
        sessions?: Array<{
          __typename: "OfficeHoursSessions";
          title: string;
          performer?: string | null;
          designation?: string | null;
          description?: string | null;
          date: string;
          link?: string | null;
          interestGroups?: Array<string | null> | null;
          poster_thumbnail?: string | null;
        } | null> | null;
      } | null;
    } | null> | null;
  };
};

export type SaltMangoTreeQueryVariables = Exact<{
  relativePath: Scalars["String"]["input"];
}>;

export type SaltMangoTreeQuery = {
  __typename?: "Query";
  saltMangoTree: {
    __typename: "SaltMangoTree";
    id: string;
    _sys: {
      __typename?: "SystemInfo";
      filename: string;
      basename: string;
      hasReferences?: boolean | null;
      breadcrumbs: Array<string>;
      path: string;
      relativePath: string;
      extension: string;
    };
    episodes?: Array<{
      __typename: "SaltMangoTreeEpisodes";
      topic: string;
      campus: string;
      zone?: string | null;
      date: string;
      description?: string | null;
      link?: string | null;
    } | null> | null;
  };
};

export type SaltMangoTreeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<SaltMangoTreeFilter>;
}>;

export type SaltMangoTreeConnectionQuery = {
  __typename?: "Query";
  saltMangoTreeConnection: {
    __typename?: "SaltMangoTreeConnection";
    totalCount: number;
    pageInfo: {
      __typename?: "PageInfo";
      hasPreviousPage: boolean;
      hasNextPage: boolean;
      startCursor: string;
      endCursor: string;
    };
    edges?: Array<{
      __typename?: "SaltMangoTreeConnectionEdges";
      cursor: string;
      node?: {
        __typename: "SaltMangoTree";
        id: string;
        _sys: {
          __typename?: "SystemInfo";
          filename: string;
          basename: string;
          hasReferences?: boolean | null;
          breadcrumbs: Array<string>;
          path: string;
          relativePath: string;
          extension: string;
        };
        episodes?: Array<{
          __typename: "SaltMangoTreeEpisodes";
          topic: string;
          campus: string;
          zone?: string | null;
          date: string;
          description?: string | null;
          link?: string | null;
        } | null> | null;
      } | null;
    } | null> | null;
  };
};

export type InspirationStationQueryVariables = Exact<{
  relativePath: Scalars["String"]["input"];
}>;

export type InspirationStationQuery = {
  __typename?: "Query";
  inspirationStation: {
    __typename: "InspirationStation";
    id: string;
    _sys: {
      __typename?: "SystemInfo";
      filename: string;
      basename: string;
      hasReferences?: boolean | null;
      breadcrumbs: Array<string>;
      path: string;
      relativePath: string;
      extension: string;
    };
    episodes?: Array<{
      __typename: "InspirationStationEpisodes";
      topic: string;
      campus: string;
      zone?: string | null;
      date: string;
      description?: string | null;
      link?: string | null;
    } | null> | null;
  };
};

export type InspirationStationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<InspirationStationFilter>;
}>;

export type InspirationStationConnectionQuery = {
  __typename?: "Query";
  inspirationStationConnection: {
    __typename?: "InspirationStationConnection";
    totalCount: number;
    pageInfo: {
      __typename?: "PageInfo";
      hasPreviousPage: boolean;
      hasNextPage: boolean;
      startCursor: string;
      endCursor: string;
    };
    edges?: Array<{
      __typename?: "InspirationStationConnectionEdges";
      cursor: string;
      node?: {
        __typename: "InspirationStation";
        id: string;
        _sys: {
          __typename?: "SystemInfo";
          filename: string;
          basename: string;
          hasReferences?: boolean | null;
          breadcrumbs: Array<string>;
          path: string;
          relativePath: string;
          extension: string;
        };
        episodes?: Array<{
          __typename: "InspirationStationEpisodes";
          topic: string;
          campus: string;
          zone?: string | null;
          date: string;
          description?: string | null;
          link?: string | null;
        } | null> | null;
      } | null;
    } | null> | null;
  };
};

export type SpecialEventQueryVariables = Exact<{
  relativePath: Scalars["String"]["input"];
}>;

export type SpecialEventQuery = {
  __typename?: "Query";
  specialEvent: {
    __typename: "SpecialEvent";
    id: string;
    title: string;
    description?: string | null;
    link?: string | null;
    image?: string | null;
    isLive?: boolean | null;
    order?: number | null;
    _sys: {
      __typename?: "SystemInfo";
      filename: string;
      basename: string;
      hasReferences?: boolean | null;
      breadcrumbs: Array<string>;
      path: string;
      relativePath: string;
      extension: string;
    };
  };
};

export type SpecialEventConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<SpecialEventFilter>;
}>;

export type SpecialEventConnectionQuery = {
  __typename?: "Query";
  specialEventConnection: {
    __typename?: "SpecialEventConnection";
    totalCount: number;
    pageInfo: {
      __typename?: "PageInfo";
      hasPreviousPage: boolean;
      hasNextPage: boolean;
      startCursor: string;
      endCursor: string;
    };
    edges?: Array<{
      __typename?: "SpecialEventConnectionEdges";
      cursor: string;
      node?: {
        __typename: "SpecialEvent";
        id: string;
        title: string;
        description?: string | null;
        link?: string | null;
        image?: string | null;
        isLive?: boolean | null;
        order?: number | null;
        _sys: {
          __typename?: "SystemInfo";
          filename: string;
          basename: string;
          hasReferences?: boolean | null;
          breadcrumbs: Array<string>;
          path: string;
          relativePath: string;
          extension: string;
        };
      } | null;
    } | null> | null;
  };
};

export const EventPartsFragmentDoc = gql`
    fragment EventParts on Event {
  __typename
  title
  date
  description
  link
  image
  isLive
  category
  order
}
    `;
export const OfficeHoursPartsFragmentDoc = gql`
    fragment OfficeHoursParts on OfficeHours {
  __typename
  sessions {
    __typename
    title
    performer
    designation
    description
    date
    link
    interestGroups
    poster_thumbnail
  }
}
    `;
export const SaltMangoTreePartsFragmentDoc = gql`
    fragment SaltMangoTreeParts on SaltMangoTree {
  __typename
  episodes {
    __typename
    topic
    campus
    zone
    date
    description
    link
  }
}
    `;
export const InspirationStationPartsFragmentDoc = gql`
    fragment InspirationStationParts on InspirationStation {
  __typename
  episodes {
    __typename
    topic
    campus
    zone
    date
    description
    link
  }
}
    `;
export const SpecialEventPartsFragmentDoc = gql`
    fragment SpecialEventParts on SpecialEvent {
  __typename
  title
  description
  link
  image
  isLive
  order
}
    `;
export const EventDocument = gql`
    query event($relativePath: String!) {
  event(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventParts
  }
}
    ${EventPartsFragmentDoc}`;
export const EventConnectionDocument = gql`
    query eventConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventFilter) {
  eventConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventParts
      }
    }
  }
}
    ${EventPartsFragmentDoc}`;
export const OfficeHoursDocument = gql`
    query officeHours($relativePath: String!) {
  officeHours(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OfficeHoursParts
  }
}
    ${OfficeHoursPartsFragmentDoc}`;
export const OfficeHoursConnectionDocument = gql`
    query officeHoursConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OfficeHoursFilter) {
  officeHoursConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OfficeHoursParts
      }
    }
  }
}
    ${OfficeHoursPartsFragmentDoc}`;
export const SaltMangoTreeDocument = gql`
    query saltMangoTree($relativePath: String!) {
  saltMangoTree(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SaltMangoTreeParts
  }
}
    ${SaltMangoTreePartsFragmentDoc}`;
export const SaltMangoTreeConnectionDocument = gql`
    query saltMangoTreeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SaltMangoTreeFilter) {
  saltMangoTreeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SaltMangoTreeParts
      }
    }
  }
}
    ${SaltMangoTreePartsFragmentDoc}`;
export const InspirationStationDocument = gql`
    query inspirationStation($relativePath: String!) {
  inspirationStation(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...InspirationStationParts
  }
}
    ${InspirationStationPartsFragmentDoc}`;
export const InspirationStationConnectionDocument = gql`
    query inspirationStationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: InspirationStationFilter) {
  inspirationStationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...InspirationStationParts
      }
    }
  }
}
    ${InspirationStationPartsFragmentDoc}`;
export const SpecialEventDocument = gql`
    query specialEvent($relativePath: String!) {
  specialEvent(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SpecialEventParts
  }
}
    ${SpecialEventPartsFragmentDoc}`;
export const SpecialEventConnectionDocument = gql`
    query specialEventConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SpecialEventFilter) {
  specialEventConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SpecialEventParts
      }
    }
  }
}
    ${SpecialEventPartsFragmentDoc}`;
export type Requester<C = {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>;
export function getSdk<C>(requester: Requester<C>) {
  return {
    event(
      variables: EventQueryVariables,
      options?: C,
    ): Promise<{
      data: EventQuery;
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[];
      variables: EventQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: EventQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: EventQueryVariables;
          query: string;
        },
        EventQueryVariables
      >(EventDocument, variables, options);
    },
    eventConnection(
      variables?: EventConnectionQueryVariables,
      options?: C,
    ): Promise<{
      data: EventConnectionQuery;
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[];
      variables: EventConnectionQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: EventConnectionQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: EventConnectionQueryVariables;
          query: string;
        },
        EventConnectionQueryVariables
      >(EventConnectionDocument, variables, options);
    },
    officeHours(
      variables: OfficeHoursQueryVariables,
      options?: C,
    ): Promise<{
      data: OfficeHoursQuery;
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[];
      variables: OfficeHoursQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: OfficeHoursQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: OfficeHoursQueryVariables;
          query: string;
        },
        OfficeHoursQueryVariables
      >(OfficeHoursDocument, variables, options);
    },
    officeHoursConnection(
      variables?: OfficeHoursConnectionQueryVariables,
      options?: C,
    ): Promise<{
      data: OfficeHoursConnectionQuery;
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[];
      variables: OfficeHoursConnectionQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: OfficeHoursConnectionQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: OfficeHoursConnectionQueryVariables;
          query: string;
        },
        OfficeHoursConnectionQueryVariables
      >(OfficeHoursConnectionDocument, variables, options);
    },
    saltMangoTree(
      variables: SaltMangoTreeQueryVariables,
      options?: C,
    ): Promise<{
      data: SaltMangoTreeQuery;
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[];
      variables: SaltMangoTreeQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: SaltMangoTreeQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: SaltMangoTreeQueryVariables;
          query: string;
        },
        SaltMangoTreeQueryVariables
      >(SaltMangoTreeDocument, variables, options);
    },
    saltMangoTreeConnection(
      variables?: SaltMangoTreeConnectionQueryVariables,
      options?: C,
    ): Promise<{
      data: SaltMangoTreeConnectionQuery;
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[];
      variables: SaltMangoTreeConnectionQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: SaltMangoTreeConnectionQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: SaltMangoTreeConnectionQueryVariables;
          query: string;
        },
        SaltMangoTreeConnectionQueryVariables
      >(SaltMangoTreeConnectionDocument, variables, options);
    },
    inspirationStation(
      variables: InspirationStationQueryVariables,
      options?: C,
    ): Promise<{
      data: InspirationStationQuery;
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[];
      variables: InspirationStationQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: InspirationStationQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: InspirationStationQueryVariables;
          query: string;
        },
        InspirationStationQueryVariables
      >(InspirationStationDocument, variables, options);
    },
    inspirationStationConnection(
      variables?: InspirationStationConnectionQueryVariables,
      options?: C,
    ): Promise<{
      data: InspirationStationConnectionQuery;
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[];
      variables: InspirationStationConnectionQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: InspirationStationConnectionQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: InspirationStationConnectionQueryVariables;
          query: string;
        },
        InspirationStationConnectionQueryVariables
      >(InspirationStationConnectionDocument, variables, options);
    },
    specialEvent(
      variables: SpecialEventQueryVariables,
      options?: C,
    ): Promise<{
      data: SpecialEventQuery;
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[];
      variables: SpecialEventQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: SpecialEventQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: SpecialEventQueryVariables;
          query: string;
        },
        SpecialEventQueryVariables
      >(SpecialEventDocument, variables, options);
    },
    specialEventConnection(
      variables?: SpecialEventConnectionQueryVariables,
      options?: C,
    ): Promise<{
      data: SpecialEventConnectionQuery;
      errors?: { message: string; locations: { line: number; column: number }[]; path: string[] }[];
      variables: SpecialEventConnectionQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: SpecialEventConnectionQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: SpecialEventConnectionQueryVariables;
          query: string;
        },
        SpecialEventConnectionQueryVariables
      >(SpecialEventConnectionDocument, variables, options);
    },
  };
}
export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, type TinaClient } from "tinacms/dist/client";

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string;
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], "body" | "method">;
    },
    client,
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl;
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf("/");
      url = client.apiUrl.substring(0, index + 1) + options.branch;
    }
    const data = await client.request(
      {
        query: doc,
        variables: vars,
        url,
      },
      options,
    );

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} };
  };

  return requester;
};

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      }),
    ),
  );

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client);
  return getSdk(requester);
};
